
#include "SPI_driver.h"

void spi_init(void){

    RCC->APB1ENR |= RCC_APB2ENR_SPI1EN; //Enable SPI clock
    
    /*Enable GPIO clock for spi 1*/
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;

    //Set up GPIO
    SPI1_GPIO->MODER |= GPIO_MODER_MODER5_1 | GPIO_MODER_MODER6_1 | GPIO_MODER_MODER7_1 | GPIO_MODER_MODER1_0 | GPIO_MODER_MODER4_0 | GPIO_MODER_MODER8_0 | GPIO_MODER_MODER9_0; //Alternate function and GPIO

    SPI1_GPIO->PUPDR |= GPIO_PUPDR_PUPDR1_0 | GPIO_PUPDR_PUPDR4_0 | GPIO_PUPDR_PUPDR8_0 | GPIO_PUPDR_PUPDR9_0; //GPIO pull up
    
    SPI1_GPIO->AFR[0] |= SPI1_CLK | SPI1_MISO | SPI1_MOSI; //Set GPIO to MOSI

    /* SPI CONFIGURATION */

    T_SPI->CR1 |= SPI_CR1_BIDIMODE | SPI_CR1_SPE | SPI_CR1_MSTR | SPI_CR1_CPOL | SPI_CR1_CPHA;

}

void spi_dma_init(void){}

void spi_send(void){}