#ifndef PROJECT_SETUP_H
#define PROJECT_SETUP_H

#define DATAFILE_HEADER_NODE 			8

#define DATAFILE_HEADER_OPERATOR_ID 	1
#define DATAFILE_HEADER_DATE_ID 		2
#define DATAFILE_HEADER_DESCRIPTION_ID 	3

#define DATAFILE_HEADER_TEST_OPERATOR 	"Nathan Roussel"

#define DATAFILE_HEADER_DATE_YEAR 			20
#define DATAFILE_HEADER_DATE_MONTH 			10
#define DATAFILE_HEADER_DATE_DAY 			12
#define DATAFILE_HEADER_DESCRIPTION 	"DAQ from coldflow test"

#endif //PROJECT_SETUP_H
